<script setup lang="ts">
import { onBeforeUnmount, onMounted, ref } from 'vue'
import { ElMessage } from 'element-plus'
import { useRouter } from 'vue-router'
import { APIError, api } from '@/api'

type Item = { id: number; dialogType: string; dialogKey: string; dialogId: number; messageId: number; messageText?: string; originalName: string; size: number; finalPath?: string; startedAt?: string; finishedAt?: string; elapsedMs: number; attempts: number; status: string; error?: string }
type Job = { id: string; sourceUrl: string; dialogType: string; dialogKey: string; dialogName: string; hasPublicLink: boolean; messageText?: string; status: string; attempts: number; error?: string; createdAt: string; totalItems: number; completedItems: number; items?: Item[] }
type Page = { jobs: Job[]; total: number; pageSize: number; nextCursor?: string; revision: number }
type Submission = { requestId: string; job: Job; created: boolean; duplicate: boolean; reactivated?: boolean }
type ChatJob = { id: string; sourceUrl: string; dialogType: string; dialogName: string; startMessageId: number; upperMessageId: number; listenNew: boolean; status: string; scanState: string; error?: string; discovered: number; completed: number; failed: number }
type ChatPage = { jobs: ChatJob[]; total: number; pageSize: number; nextCursor?: string; revision: number }
type FileProgress = { dialogType: string; dialogKey: string; dialogId: number; messageId: number; downloaded: number; total: number; speedBps: number }
const router = useRouter(); const activeTab = ref('message'); const url = ref(''); const jobs = ref<Job[]>([]); const total = ref(0); const pageSize = 10; const cursorHistory = ref<string[]>(['']); const pageIndex = ref(0); const nextCursor = ref(''); const creating = ref(false); const jobTable = ref(); const liveProgress = ref<Record<string, FileProgress>>({}); const streamNow = ref(Date.now()); const chatURL = ref(''); const chatListenNew = ref(false); const chatJobs = ref<ChatJob[]>([]); const chatTotal = ref(0); const chatCursorHistory = ref<string[]>(['']); const chatPageIndex = ref(0); const chatNextCursor = ref(''); const creatingChat = ref(false); let progressStream: EventSource | undefined; let knownRevision = -1; let pendingRevision = -1; let loading = false; let loadingChats = false
async function load() { if (loading) return; loading = true; try { const cursor = cursorHistory.value[pageIndex.value] || ''; const result = await api<Page>(`/api/downloads?cursor=${encodeURIComponent(cursor)}&pageSize=${pageSize}`); jobs.value = result.jobs || []; total.value = result.total; nextCursor.value = result.nextCursor || ''; knownRevision = result.revision } catch (error) { if (error instanceof APIError && error.status === 401) await router.replace('/login'); else ElMessage.error(error instanceof Error ? error.message : '读取任务失败') } finally { loading = false; if (pendingRevision > knownRevision) { pendingRevision = -1; void load() } } }
async function nextPage() { if (!nextCursor.value) return; cursorHistory.value = cursorHistory.value.slice(0, pageIndex.value + 1); cursorHistory.value.push(nextCursor.value); pageIndex.value++; await load() }
async function previousPage() { if (pageIndex.value < 1) return; pageIndex.value--; await load() }
async function loadChats() { if (loadingChats) return; loadingChats = true; try { const cursor = chatCursorHistory.value[chatPageIndex.value] || ''; const result = await api<ChatPage>(`/api/chat-downloads?cursor=${encodeURIComponent(cursor)}&pageSize=${pageSize}`); chatJobs.value = result.jobs || []; chatTotal.value = result.total; chatNextCursor.value = result.nextCursor || ''; knownRevision = Math.max(knownRevision, result.revision) } catch (error) { if (error instanceof APIError && error.status === 401) await router.replace('/login'); else ElMessage.error(error instanceof Error ? error.message : '读取会话任务失败') } finally { loadingChats = false } }
async function nextChatPage() { if (!chatNextCursor.value) return; chatCursorHistory.value = chatCursorHistory.value.slice(0, chatPageIndex.value + 1); chatCursorHistory.value.push(chatNextCursor.value); chatPageIndex.value++; await loadChats() }
async function previousChatPage() { if (chatPageIndex.value < 1) return; chatPageIndex.value--; await loadChats() }
const detailLoads = new Map<string, Promise<void>>()
function toggleRow(job: Job) { jobTable.value?.toggleRowExpansion(job) }
async function loadItems(job: Job) { if (job.items) return; const pending = detailLoads.get(job.id); if (pending) return pending; const request = api<Job>(`/api/downloads/${job.id}`).then((detail) => { job.items = detail.items || [] }).catch((error) => { ElMessage.error(error instanceof Error ? error.message : '读取文件明细失败') }).finally(() => { detailLoads.delete(job.id) }); detailLoads.set(job.id, request); return request }
function onExpandChange(job: Job, expandedRows: Job[]) { if (expandedRows.some((row) => row.id === job.id)) void loadItems(job) }
async function create() { creating.value = true; try { const result = await api<Submission>('/api/downloads', { method: 'POST', body: JSON.stringify({ url: url.value }) }); url.value = ''; cursorHistory.value = ['']; pageIndex.value = 0; await load(); ElMessage.success(result.reactivated ? '已取消任务已重新加入队列' : result.duplicate ? '该消息已关联到现有下载任务' : '下载任务已加入队列') } catch (error) { ElMessage.error(error instanceof Error ? error.message : '创建失败') } finally { creating.value = false } }
async function createChat() { creatingChat.value = true; try { await api<ChatJob>('/api/chat-downloads', { method: 'POST', body: JSON.stringify({ url: chatURL.value, listenNew: chatListenNew.value }) }); chatURL.value = ''; chatCursorHistory.value = ['']; chatPageIndex.value = 0; await loadChats(); ElMessage.success('会话下载任务已创建，正在索引媒体') } catch (error) { ElMessage.error(error instanceof Error ? error.message : '创建失败') } finally { creatingChat.value = false } }
async function control(job: Job, action: 'pause' | 'resume' | 'retry' | 'cancel' | 'delete') { try { await api(`/api/downloads/${job.id}/${action}`, { method: action === 'delete' ? 'DELETE' : 'POST' }); if (action === 'delete' && jobs.value.length === 1 && pageIndex.value > 0) pageIndex.value--; await load(); ElMessage.success(action === 'delete' ? '任务已删除' : '任务状态已更新') } catch (error) { ElMessage.error(error instanceof Error ? error.message : '操作失败') } }
async function chatControl(job: ChatJob, action: 'pause' | 'resume' | 'retry' | 'cancel' | 'delete') { try { await api(`/api/chat-downloads/${job.id}/${action}`, { method: action === 'delete' ? 'DELETE' : 'POST' }); if (action === 'delete' && chatJobs.value.length === 1 && chatPageIndex.value > 0) chatPageIndex.value--; await loadChats(); ElMessage.success(action === 'delete' ? '会话任务已删除' : '会话任务状态已更新') } catch (error) { ElMessage.error(error instanceof Error ? error.message : '操作失败') } }
function type(status: string) { return status === 'completed' || status === 'downloaded' ? 'success' : status === 'failed' ? 'danger' : status === 'partial' || status === 'running' ? 'warning' : 'info' }
function statusLabel(status: string) { return ({ queued: '排队中', running: '下载中', downloaded: '下载完成', paused: '已暂停', completed: '已完成', partial: '部分完成', failed: '失败', cancelled: '已取消', scanning: '索引中', downloading: '下载中', listening: '监听中' } as Record<string, string>)[status] || status }
function statusTip(item: Item) { return item.error || ({ queued: '等待可用下载槽位，尚未开始传输', running: '正在下载文件', downloaded: '下载已完成，等待移动到最终路径', paused: '下载已暂停，可恢复', completed: '文件已下载并移动至最终路径', failed: '文件下载或处理失败', cancelled: '下载已取消' } as Record<string, string>)[item.status] || item.status }
function dialogTypeLabel(value: string) { return ({ user: '私聊', chat: '群组', channel: '频道', self: '收藏消息', legacy: '会话' } as Record<string, string>)[value] || '会话' }
function sourceLabel(job: Job) { return job.hasPublicLink ? job.sourceUrl : '私有会话（无公开消息链接）' }
function progressFor(item: Item) { return liveProgress.value[`${item.dialogKey}:${item.messageId}`] }
function byteLabel(value: number) { if (!value) return '0 B'; const units = ['B', 'KB', 'MB', 'GB', 'TB']; let index = 0; let result = value; while (result >= 1024 && index < units.length - 1) { result /= 1024; index++ }; return `${result >= 10 || index === 0 ? result.toFixed(0) : result.toFixed(1)} ${units[index]}` }
function fileSizeLabel(value: number) { if (!Number.isFinite(value) || value <= 0) return '—'; const unit = value >= 1024 ** 3 ? 'GB' : value >= 1024 ** 2 ? 'MB' : value >= 1024 ? 'KB' : 'B'; const divisor = unit === 'GB' ? 1024 ** 3 : unit === 'MB' ? 1024 ** 2 : unit === 'KB' ? 1024 : 1; return `${Number((value / divisor).toFixed(2))} ${unit}` }
function sizeLabel(item: Item) { return fileSizeLabel(progressFor(item)?.total || item.size) }
function progressLabel(item: Item) { if (item.status === 'completed' || item.status === 'downloaded') return '100%'; const value = progressFor(item); if (!value || !value.total) return '—'; return `${Math.min(100, Math.floor(value.downloaded * 100 / value.total))}%` }
function durationSeconds(item: Item) { const base = (item.elapsedMs || 0) / 1000; if (!item.startedAt) return base; const start = Date.parse(item.startedAt); const end = item.finishedAt ? Date.parse(item.finishedAt) : streamNow.value; return Number.isFinite(start) && Number.isFinite(end) ? base + Math.max(0, (end - start) / 1000) : base }
function durationLabel(item: Item) { const seconds = Math.floor(durationSeconds(item)); if (!item.startedAt && !item.elapsedMs) return '—'; const hours = Math.floor(seconds / 3600); const minutes = Math.floor(seconds % 3600 / 60); const remainder = seconds % 60; return `${String(hours).padStart(2, '0')}:${String(minutes).padStart(2, '0')}:${String(remainder).padStart(2, '0')}` }
function speedLabel(item: Item) { if (item.status === 'completed' || item.status === 'downloaded') { const seconds = durationSeconds(item); return item.size > 0 && seconds >= 1 ? `${byteLabel(item.size / seconds)}/s` : '—' }; const value = progressFor(item); return value?.speedBps ? `${byteLabel(value.speedBps)}/s` : '—' }
async function logout() { await api('/api/auth/logout', { method: 'POST' }); await router.replace('/login') }
onMounted(async () => { const s = await api<{ authenticated: boolean }>('/api/auth/session'); if (!s.authenticated) return void router.replace('/login'); await Promise.all([load(), loadChats()]); progressStream = new EventSource('/api/downloads/progress'); progressStream.onmessage = (event) => { try { const data = JSON.parse(event.data) as { files: FileProgress[]; revision: number }; streamNow.value = Date.now(); liveProgress.value = Object.fromEntries((data.files || []).map((file) => [`${file.dialogKey}:${file.messageId}`, file])); if (Number.isFinite(data.revision) && data.revision > knownRevision) { pendingRevision = Math.max(pendingRevision, data.revision); void load(); void loadChats() } } catch { /* reconnecting stream data is ignored */ } } }); onBeforeUnmount(() => { progressStream?.close() })
</script>
<template>
  <el-container class="shell">
    <el-aside width="244px"><div class="brand">TDL 管理</div><el-menu default-active="/downloads" router><el-menu-item index="/">仪表盘</el-menu-item><el-menu-item index="/accounts">登录管理</el-menu-item><el-menu-item index="/downloads">下载管理</el-menu-item><el-menu-item index="/settings">配置管理</el-menu-item></el-menu><div class="sidebar-meta"><span>上游 tdl <b>v0.20.4</b></span><span>项目版本 <b>v0.1.0</b></span></div></el-aside>
    <el-container><el-header><span>下载管理</span><el-button text @click="logout">退出管理台</el-button></el-header>
      <el-main class="downloads-page">
        <el-tabs v-model="activeTab" class="download-tabs"><el-tab-pane label="消息下载" name="message" /><el-tab-pane label="会话下载" name="chat" /></el-tabs>
        <template v-if="activeTab === 'message'">
        <el-card shadow="never" class="new-job"><el-form class="new-job-form" @submit.prevent="create"><el-input v-model="url" placeholder="Telegram 消息链接，例如 https://t.me/channel/123" /><el-button type="primary" :loading="creating" :disabled="!url" @click="create">创建下载任务</el-button></el-form></el-card>
        <el-empty v-if="!jobs.length" description="还没有下载任务。" />
        <el-table v-else ref="jobTable" :data="jobs" row-key="id" size="small" class="job-list" @row-click="toggleRow" @expand-change="onExpandChange">
          <el-table-column type="expand" width="48">
            <template #default="{ row }"><el-table :data="row.items || []" size="small" max-height="260" class="file-list"><el-table-column prop="messageId" label="消息 ID" width="100" /><el-table-column prop="originalName" label="原始文件名" min-width="180" :show-overflow-tooltip="{ popperClass: 'file-overflow-tooltip' }" /><el-table-column label="完整文件路径" min-width="260" :show-overflow-tooltip="{ popperClass: 'file-overflow-tooltip' }"><template #default="{ row: item }">{{ item.finalPath || '—' }}</template></el-table-column><el-table-column label="体积" width="105"><template #default="{ row: item }">{{ sizeLabel(item) }}</template></el-table-column><el-table-column label="进度" width="90"><template #default="{ row: item }">{{ progressLabel(item) }}</template></el-table-column><el-table-column label="速率" width="105"><template #default="{ row: item }">{{ speedLabel(item) }}</template></el-table-column><el-table-column label="耗时" width="100"><template #default="{ row: item }">{{ durationLabel(item) }}</template></el-table-column><el-table-column label="状态" width="100"><template #default="{ row: item }"><el-tooltip :content="statusTip(item)" placement="top" :show-after="150" popper-class="file-overflow-tooltip"><span class="file-status">{{ statusLabel(item.status) }}</span></el-tooltip></template></el-table-column></el-table></template>
          </el-table-column>
          <el-table-column label="对话名称" min-width="105" show-overflow-tooltip><template #default="{ row }"><span>{{ row.dialogName || '—' }}</span><small class="dialog-kind">{{ dialogTypeLabel(row.dialogType) }}</small></template></el-table-column>
          <el-table-column label="消息内容" min-width="245" :show-overflow-tooltip="{ popperClass: 'file-overflow-tooltip' }"><template #default="{ row }">{{ row.messageText || '—' }}</template></el-table-column>
          <el-table-column label="消息链接" min-width="200" show-overflow-tooltip><template #default="{ row }">{{ sourceLabel(row) }}</template></el-table-column>
          <el-table-column label="进度" width="100"><template #default="{ row }">{{ row.completedItems }}/{{ row.totalItems }} 文件</template></el-table-column>
          <el-table-column prop="status" label="状态" width="90"><template #default="{ row }"><el-tag :type="type(row.status) as any">{{ statusLabel(row.status) }}</el-tag></template></el-table-column>
          <el-table-column label="操作" width="150"><template #default="{ row }"><div class="job-actions" @click.stop><el-popconfirm v-if="row.status === 'completed' || row.status === 'failed' || row.status === 'partial' || row.status === 'cancelled'" title="删除任务记录和临时文件？不会删除已下载的最终文件。" confirm-button-text="删除" cancel-button-text="保留" @confirm="control(row, 'delete')"><template #reference><el-button text type="danger">删除</el-button></template></el-popconfirm><el-button v-if="row.status === 'failed' || row.status === 'partial'" text type="primary" @click="control(row, 'retry')">重试</el-button><el-button v-if="row.status === 'cancelled'" text type="primary" @click="control(row, 'retry')">重新开始</el-button><el-button v-if="row.status === 'paused'" text type="primary" @click="control(row, 'resume')">恢复</el-button><el-button v-if="row.status === 'queued' || row.status === 'running'" text @click="control(row, 'pause')">暂停</el-button><el-button v-if="row.status === 'queued' || row.status === 'running' || row.status === 'paused'" text type="danger" @click="control(row, 'cancel')">取消</el-button></div></template></el-table-column>
        </el-table>
        <div v-if="total > pageSize" class="pagination-wrap"><span class="pagination-total">总数 {{ total }}</span><div class="cursor-pagination"><el-button size="small" :disabled="pageIndex === 0" @click="previousPage">上一页</el-button><span class="pagination-current">第 {{ pageIndex + 1 }} 页 / 共 {{ Math.max(1, Math.ceil(total / pageSize)) }} 页</span><el-button size="small" :disabled="!nextCursor" @click="nextPage">下一页</el-button></div></div>
        </template>
        <template v-else>
          <el-card shadow="never" class="new-job"><el-form class="new-job-form" @submit.prevent="createChat"><el-input v-model="chatURL" placeholder="频道或群组链接；带消息 ID 时从该消息开始" /><el-checkbox v-model="chatListenNew">下载历史完成后监听新媒体</el-checkbox><el-button type="primary" :loading="creatingChat" :disabled="!chatURL" @click="createChat">创建会话任务</el-button></el-form></el-card>
          <el-empty v-if="!chatJobs.length" description="还没有会话下载任务。" />
          <el-table v-else :data="chatJobs" size="small" class="job-list">
            <el-table-column label="对话名称" min-width="190" show-overflow-tooltip><template #default="{ row }"><span>{{ row.dialogName || '—' }}</span><small class="dialog-kind">{{ dialogTypeLabel(row.dialogType) }}</small></template></el-table-column>
            <el-table-column label="下载范围" min-width="170"><template #default="{ row }">{{ row.startMessageId || '最早' }} — {{ row.upperMessageId }}</template></el-table-column>
            <el-table-column label="媒体进度" width="155"><template #default="{ row }">{{ row.completed }}/{{ row.discovered }}<span v-if="row.failed"> · {{ row.failed }} 失败</span></template></el-table-column>
            <el-table-column label="新媒体监听" width="120"><template #default="{ row }">{{ row.listenNew ? '已开启' : '未开启' }}</template></el-table-column>
            <el-table-column label="状态" width="95"><template #default="{ row }"><el-tooltip v-if="row.error" :content="row.error"><el-tag :type="type(row.status) as any">{{ statusLabel(row.status) }}</el-tag></el-tooltip><el-tag v-else :type="type(row.status) as any">{{ statusLabel(row.status) }}</el-tag></template></el-table-column>
            <el-table-column label="操作" width="180"><template #default="{ row }"><div class="job-actions"><el-popconfirm v-if="['completed','failed','partial','cancelled'].includes(row.status)" title="删除会话任务和临时文件？不会删除已下载的最终文件。" confirm-button-text="删除" cancel-button-text="保留" @confirm="chatControl(row, 'delete')"><template #reference><el-button text type="danger">删除</el-button></template></el-popconfirm><el-button v-if="['failed','partial','cancelled'].includes(row.status) || row.failed > 0" text type="primary" @click="chatControl(row, 'retry')">{{ row.failed > 0 && row.status === 'listening' ? '重试失败项' : '重新开始' }}</el-button><el-button v-if="row.status === 'paused'" text type="primary" @click="chatControl(row, 'resume')">恢复</el-button><el-button v-if="['queued','scanning','downloading','listening'].includes(row.status)" text @click="chatControl(row, 'pause')">暂停</el-button><el-button v-if="['queued','scanning','downloading','listening','paused'].includes(row.status)" text type="danger" @click="chatControl(row, 'cancel')">取消</el-button></div></template></el-table-column>
          </el-table>
          <div v-if="chatTotal > pageSize" class="pagination-wrap"><span class="pagination-total">总数 {{ chatTotal }}</span><div class="cursor-pagination"><el-button size="small" :disabled="chatPageIndex === 0" @click="previousChatPage">上一页</el-button><span class="pagination-current">第 {{ chatPageIndex + 1 }} 页 / 共 {{ Math.max(1, Math.ceil(chatTotal / pageSize)) }} 页</span><el-button size="small" :disabled="!chatNextCursor" @click="nextChatPage">下一页</el-button></div></div>
        </template>
      </el-main>
    </el-container>
  </el-container>
</template>

<style scoped>
.dialog-kind { margin-left: 6px; color: var(--el-text-color-secondary); font-size: 12px; white-space: nowrap; }
</style>
